
from typing import Protocol, Any, Mapping, List, Tuple

class SemanticsPlugin(Protocol):
    name: str
    base_domain: str
    def persona_prefix(self, mood_vector: Mapping[str, float]) -> str: ...
    def pre_text(self, text: str) -> str: ...
    def post_text(self, text: str) -> str: ...
    def pre_embed(self, text: str) -> str: ...
    def post_embed(self, vec) -> Any: ...
    def rerank(self, candidates: List[Tuple[str, float]]) -> List[Tuple[str, float]]: ...

class PromptPack(Protocol):
    def render(self, key: str, **vars) -> str: ...
